name: "❓ Ask the Host"
description: "Submit a question to the host and you might get an answer on the next episode."
title: "[ASK HOST] "
labels:
  - "question"
body:
- type: input
  id: caller-name
  attributes:
    label: Name
    placeholder: "Confused in Cleveland"
    validations:
    required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      options:
        - Topic #1
        - Topic #2
        - Topic #3
        - Topic #4
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: ""
    validations:
      required: true

  - type: checkboxes
    id: permission
    attributes:
      label: Permission
      options:
        - label: By submitting this form, you give the host and the show full permission to use it in an episode at their sole discretion.
          required: true

