name: "🎙️Share a Story"
description: ""
title: "[Share a Story] "
labels:
  - "call-in: story"
body:
  - type: markdown
    attributes:
      value: |
        

  - type: input
    id: caller-name
    attributes:
      label: Name
      placeholder: "Your name"
    validations:
      required: true

  - type: textarea
    id: story
    attributes:
      label: Share your story:
      description: 
      placeholder: ""
    validations:
      required: true

  - type: checkboxes
    id: permission
    attributes:
      label: Permission
      options:
        - label: By submitting this form, you give the host and the show full permission to use it in an episode at their sole discretion.
          required: true

